name: Tourism Package Prediction MLOps Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'tourism_package/**'
      - 'tourism.csv'
      - '.github/workflows/pipeline.yml' # Trigger on changes to the workflow itself
  workflow_dispatch: # Allows manual trigger

jobs:
  run_mlops_pipeline:
    runs-on: ubuntu-latest
    
    # Define environment variables (HF_TOKEN is set as a secret)
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: 3. Install dependencies
      run: |
        # Install packages required for prep, dev, and hosting
        pip install pandas scikit-learn mlflow datasets huggingface_hub joblib numpy

    - name: 4. Create artifacts directory
      run: |
        mkdir -p tourism_package/artifacts
        mkdir -p tourism_package/hosting
        mkdir -p tourism_package/deployment

    - name: 5. Run Data Preparation (prep.py)
      run: |
        python tourism_package/prep.py
      # Continues on failure is set to false by default, so a failure here stops the pipeline.

    - name: 6. Run Model Development & Experimentation (dev.py)
      run: |
        python tourism_package/model_building/dev.py

    - name: 7. Commit and Push MLflow/Artifacts (Optional but good for tracking)
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "CI/CD: Push MLflow logs and artifacts after dev.py run"
        file_pattern: 'mlruns/** artifacts/**'
        branch: main
        
    # --- Deployment Phase (Only if previous steps succeeded) ---
    - name: 8. Copy Deployment Files for Hosting
      run: |
        # Copy the Dockerfile and requirements.txt (which are writefiled locally)
        cp tourism_package/deployment/Dockerfile tourism_package/deployment/Dockerfile
        cp tourism_package/deployment/requirements.txt tourism_package/deployment/requirements.txt
        cp tourism_package/deployment/app.py tourism_package/deployment/app.py
        cp tourism_package/hosting/hosting.py tourism_package/hosting/hosting.py

    - name: 9. Deploy to Hugging Face Space (hosting.py)
      run: |
        python tourism_package/hosting/hosting.py
