name: Tourism Package Prediction MLOps Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'tourism_package/**'
      - '.github/workflows/pipeline.yml'
  workflow_dispatch:

jobs:
  run_mlops_pipeline:
    runs-on: ubuntu-latest
    
    # --- CRITICAL FIX START: Grant Write Permission for Git Operations ---
    permissions:
      contents: write
    # -------------------------------- CRITICAL FIX END -------------------

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v4

    - name: 2. Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: 3. Install dependencies
      run: |
        # Install packages required for prep, dev, and hosting
        pip install pandas scikit-learn mlflow datasets huggingface_hub joblib numpy

    - name: 4. Create artifacts directory
      run: |
        # Create artifacts folder adjacent to the scripts, if needed, or just at the root
        mkdir -p tourism_package/model_building/artifacts
        
    # Assuming 'data_register.py' handles the initial data upload (Step 1 of Rubric)
    # If data registration is inside prep.py, you can comment this out. 
    # Since you listed it, I'll include it for a potential separate script.
    - name: 5. Run Data Registration (data_register.py)
      run: |
        python tourism_package/model_building/data_register.py
        
    - name: 6. Run Data Preparation (prep.py)
      run: |
        # CORRECTED PATH based on your new structure
        python tourism_package/model_building/prep.py

    - name: 7. Run Model Development & Experimentation (dev_experiment.py)
      run: |
        # CORRECTED PATH and filename
        python tourism_package/model_building/dev_experiment.py 

    - name: 8. Commit and Push MLflow/Artifacts (Optional but good for tracking)
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "CI/CD: Push MLflow logs and artifacts"
        file_pattern: 'mlruns/** artifacts/**'
        branch: main
        
    - name: 9. Deploy to Hugging Face Space (hosting.py)
      run: |
        # Path is tourism_package/hosting/hosting.py
        python tourism_package/hosting/hosting.py
